backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

  publish_mode: editorial_workflow
media_folder: "web/src/assets/uploads" # Media files will be stored in the repo under web/src/assets/uploads
public_folder: "uploads" # The src attribute for uploaded media will begin with /uploads

collections:
  - name: "post"
    label: "Blog Post"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Image', name: 'image', widget: 'string' }
      - { label: 'Image Alt', name: 'imageAlt', widget: 'string' }
